[tool.poetry]
name = "project-name"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "8.1.7"
Flask = "3.0.0"
Flask-Cors = "4.0.0"
Flask-JWT-Extended = "4.6.0"
Flask-SQLAlchemy = "3.0.1"
greenlet = "2.0.2"
gunicorn = "20.1.0"
itsdangerous = "2.1.2"
python-dotenv = "1.0.1"
SQLAlchemy = "1.4.18"
tabulate = "0.9.0"
Werkzeug = "3.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"